# Generated by Django 4.2.3 on 2023-11-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.CharField(default='2023-11-11 20:53', max_length=70),
        ),
    ]
